### PR TITLE
Rework Schedule (including Agenda and My Agenda)

### PR DESCRIPTION
**Pull request by pvtri96**
Agenda

screenshot_1506492160

My Agenda

screenshot_1506493368

### CODE REVIEW

**Comment by lybaokhanh** [comment]
the background card for each activity is too dark, please using opacity instead

image

**Comment by lybaokhanh** [comment]
When the date is today or tomorrow you need to change the Tab name Today, Tomorrow so the end-user can easily to turn back on the current day.

image

**Comment by lybaokhanh** [comment]
The style of My Agenda has been changed.

image

**Comment by pvtri96** [comment]
@dungle1811 Please take a look at this.

**Comment by dungle1811** [comment]
How can I cancel any activities from My Agenda ?
The activities have been occurred should be blur.
The purple color is ugly. Please change color. You can use 2 main colors are white and orange.

**Comment by pvtri96** [comment]
@dungle1811 you can press on the eye icon to cancel an activity. This will make the activity blur, like the "Short Talk" activity.

**Comment by lybaokhanh** [comment]
- Change pink to blue
- Implement DatePicker when user click month of agenda on header

image

**Comment by lybaokhanh** [comment]
Final My Agenda UI
image

**Pull request merged**
